# Generated by Django 5.0.1 on 2025-09-04 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="file",
            field=models.FileField(default=None, upload_to=""),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_hash",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file_url",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="user",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
