# Generated by Django 5.0.1 on 2025-09-09 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_file_fileversion_file_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileversion",
            name="file",
        ),
    ]
