# Generated by Django 5.0.1 on 2025-09-13 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_remove_fileversion_file"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
