# Generated by Django 5.0.1 on 2025-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_remove_fileversion_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, verbose_name="Username for User"),
        ),
    ]
