# Generated by Django 5.0.1 on 2025-09-13 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="read_permissions",
            field=models.ManyToManyField(related_name="read_permissions", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="write_permissions",
            field=models.ManyToManyField(related_name="write_permissions", to=settings.AUTH_USER_MODEL),
        ),
    ]
